version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  kics: checkmarx-kics/kics-scan@1.0.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - kics/kics_scan:
          path: .
          output_formats: sarif
          output_path: results.sarif
      - display results:
        steps:
          - run:
            name: display results
            command: |
              cat results.json
